const fs = require("fs");
const path = require("path");

const configTemplate = `
// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

export const config = {
  API_URL: "${process.env.API_URL}",
  SIGNALOID_URL: "${process.env.SIGNALOID_URL}"
};
`;

const configPath = path.join(__dirname, "..", "src", "config", "env.config.ts");
fs.writeFileSync(configPath, configTemplate.trim());
console.log(`✅ Generated config file with environment variables.`);
